"""Pydantic schemas for Natural Language Query Understanding QueryPlan."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

MAX_WEEKDAY = 6


class ParticipantHint(BaseModel):
    """Participant hint extracted from natural language."""

    name: str | None = None
    email: str | None = None

    model_config = ConfigDict(extra="forbid")


class DateRangeIntent(BaseModel):
    """Structured relative or calendar date range intent."""

    kind: Literal[
        "today",
        "yesterday",
        "this_week",
        "last_week",
        "this_month",
        "last_month",
        "this_year",
        "last_year",
        "past_days",
        "weekday",
    ]
    days: int | None = None
    weekday: int | None = None
    period: Literal["full_day", "morning", "afternoon", "evening"] | None = None

    model_config = ConfigDict(extra="forbid")

    @model_validator(mode="after")
    def validate_date_range(self) -> DateRangeIntent:
        """Validate date range fields based on kind."""
        if self.kind == "past_days":
            if self.days is None or self.days <= 0:
                raise ValueError("past_days requires days to be an integer > 0")
            if self.weekday is not None:
                raise ValueError("past_days requires weekday to be None")
        elif self.kind == "weekday":
            if self.weekday is None or self.weekday < 0 or self.weekday > MAX_WEEKDAY:
                raise ValueError(
                    "weekday requires weekday to be an integer between 0 and 6 (inclusive)"
                )
            if self.days is not None:
                raise ValueError("weekday requires days to be None")
        else:
            if self.days is not None or self.weekday is not None:
                raise ValueError(f"{self.kind} requires days and weekday to be None")
        return self


class MailQueryPlan(BaseModel):
    """Canonical domain QueryPlan generated by query understanding LLM."""

    query: str | None = None
    sender: ParticipantHint | None = None
    participants: list[ParticipantHint] = Field(default_factory=list)
    recipients: list[ParticipantHint] = Field(default_factory=list)
    folder: str | None = None
    account: str | None = None
    is_read: bool | None = None
    has_attachments: bool | None = None
    date_range: DateRangeIntent | None = None
    retrieval_intent: Literal["keyword", "semantic", "mixed"] = "keyword"

    model_config = ConfigDict(extra="forbid")
